name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Upgrade pip, install package, install requirements, build docs
        run: |
          pip install --upgrade pip
          pip install sphinx>=7.4
          pip install -e .
          pip install -r ./docs/requirements.txt
          pip uninstall -y pyqt5
          pip install pyqt6
          pip install opencv-python
          pip install opencv-python-headless
          sphinx-build docs ./docs/_build/html/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/docs'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
